import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useSession } from "next-auth/react";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`bg-[#091028] ${inter.className}`}>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
